package GUI;

import BUS.BorrowBUS;
import BUS.BorrowDetailBUS;
import BUS.ReaderBUS;

import BUS.StaffBUS;
import DAL.BorrowDAL;
import DAL.BorrowDetailDAL;
import DAL.ReaderDAL;
import DAL.StaffDAL;
import DTO.ReaderDTO;
import DTO.StaffDTO;
import DTO.BorrowDTO;
import DTO.BorrowDetailDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Timer;
import java.util.*;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hoangtuan
 */
public class BorrowGUI extends javax.swing.JPanel {

    private String borrow_date;
    public static String id;
    StaffDTO staff = new StaffDTO();
    ReaderDTO reader = new ReaderDTO();
    BorrowDTO borrow = new BorrowDTO();
    DefaultTableModel dtBorrow;
    DefaultTableModel dtBorrowDetail;
    ButtonGroup statusGroup;
    StaffBUS staffBUS = new StaffBUS();
    ReaderBUS readerBUS = new ReaderBUS();
    BorrowBUS borrowBUS = new BorrowBUS();
    BorrowDetailBUS borrowDetailBUS = new BorrowDetailBUS();

    public BorrowGUI() {
        initComponents();
        loadBorrow();
        loadBorrowDetail();
        dtBorrow = (DefaultTableModel) tbBorrow.getModel();
        dtBorrowDetail = (DefaultTableModel) tbBorrowDetail.getModel();
        setVisible(true);
        statusGroup = new ButtonGroup();
        statusGroup.add(rdmuon);
        statusGroup.add(rdtra);
        loadStaffId();
        loadReaderId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBorrowId = new javax.swing.JTextField();
        cbStaffId = new javax.swing.JComboBox<>();
        cbReaderId = new javax.swing.JComboBox<>();
        dateChooser = new com.toedter.calendar.JDateChooser();
        rdmuon = new javax.swing.JRadioButton();
        rdtra = new javax.swing.JRadioButton();
        btnAddBorrow = new javax.swing.JButton();
        btnDeleteBorrow = new javax.swing.JButton();
        btnEditBorrow = new javax.swing.JButton();
        btnResetBorrow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBorrow = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnSearchBorrow = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBorrowDetail = new javax.swing.JTable();
        btnPunish = new javax.swing.JButton();
        btnListPunish = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        dateChooser_pay = new com.toedter.calendar.JDateChooser();
        txtNote = new javax.swing.JTextField();
        btnAddBorrowDetail = new javax.swing.JButton();
        btnDeleteBorrowDetail = new javax.swing.JButton();
        btnEditBorrowDetail = new javax.swing.JButton();
        btnResetBorrowDetail = new javax.swing.JButton();
        txtBookIdBorrow = new javax.swing.JTextField();
        txtSearchBorrow = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Mã PM");

        jLabel2.setText("Mã NV");

        jLabel3.setText("Mã Độc Giả");

        jLabel4.setText("Ngày Mượn");

        jLabel5.setText("Tình Trạng");

        txtBorrowId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBorrowIdActionPerformed(evt);
            }
        });

        rdmuon.setText("Mượn");
        rdmuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdmuonActionPerformed(evt);
            }
        });

        rdtra.setText("Đã Trả");

        btnAddBorrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11_add.png"))); // NOI18N
        btnAddBorrow.setText("Thêm");
        btnAddBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBorrowActionPerformed(evt);
            }
        });

        btnDeleteBorrow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteBorrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/14_delete.png"))); // NOI18N
        btnDeleteBorrow.setText("Xóa");
        btnDeleteBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBorrowActionPerformed(evt);
            }
        });

        btnEditBorrow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditBorrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/15_update.png"))); // NOI18N
        btnEditBorrow.setText("Sửa");
        btnEditBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBorrowActionPerformed(evt);
            }
        });

        btnResetBorrow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnResetBorrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/13_reset.png"))); // NOI18N
        btnResetBorrow.setText("Tải lại");
        btnResetBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetBorrowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtBorrowId)
                        .addComponent(cbStaffId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbReaderId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdmuon)
                        .addGap(39, 39, 39)
                        .addComponent(rdtra)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetBorrow))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBorrowId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnAddBorrow))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbReaderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnDeleteBorrow)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditBorrow))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rdmuon)
                            .addComponent(rdtra))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetBorrow)
                        .addGap(16, 16, 16))))
        );

        tbBorrow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu Mượn", "Mã Nhân Viên", "Mã Độc Giả", "Ngày Mượn", "Tình Trạng"
            }
        ));
        tbBorrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBorrowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBorrow);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tìm kiếm ");

        btnSearchBorrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/12_search.png"))); // NOI18N
        btnSearchBorrow.setText("Tìm");
        btnSearchBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBorrowActionPerformed(evt);
            }
        });

        tbBorrowDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã CTPM", "Mã PM", "Mã Sách", "Ngày Trả", "Ghi Chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbBorrowDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBorrowDetailMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbBorrowDetail);

        btnPunish.setText("Phạt");
        btnPunish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPunishActionPerformed(evt);
            }
        });

        btnListPunish.setText(" Danh Sách Phạt");
        btnListPunish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPunishActionPerformed(evt);
            }
        });

        jLabel7.setText("Mã Sách");

        jLabel8.setText("Ngày Trả");

        jLabel9.setText("Ghi Chú");

        btnBook.setText("Chọn");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnAddBorrowDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11_add.png"))); // NOI18N
        btnAddBorrowDetail.setText("Thêm");
        btnAddBorrowDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBorrowDetailActionPerformed(evt);
            }
        });

        btnDeleteBorrowDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/14_delete.png"))); // NOI18N
        btnDeleteBorrowDetail.setText("Xóa");
        btnDeleteBorrowDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBorrowDetailActionPerformed(evt);
            }
        });

        btnEditBorrowDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/15_update.png"))); // NOI18N
        btnEditBorrowDetail.setText("Sửa");
        btnEditBorrowDetail.setToolTipText("");
        btnEditBorrowDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBorrowDetailActionPerformed(evt);
            }
        });

        btnResetBorrowDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/13_reset.png"))); // NOI18N
        btnResetBorrowDetail.setText("Tải lại");
        btnResetBorrowDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetBorrowDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddBorrowDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditBorrowDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnResetBorrowDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteBorrowDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBookIdBorrow, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooser_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnBook)
                    .addComponent(txtBookIdBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(dateChooser_pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBorrowDetail)
                    .addComponent(btnDeleteBorrowDetail))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditBorrowDetail)
                    .addComponent(btnResetBorrowDetail))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnSearchBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPunish)
                                .addGap(26, 26, 26)
                                .addComponent(btnListPunish)
                                .addGap(76, 76, 76))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPunish)
                        .addComponent(btnListPunish))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtSearchBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBorrowIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBorrowIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBorrowIdActionPerformed

    private void rdmuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdmuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdmuonActionPerformed

    private void btnResetBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetBorrowActionPerformed
        loadBorrow();
        loadReaderId();
        loadStaffId();
    }//GEN-LAST:event_btnResetBorrowActionPerformed

    private void btnDeleteBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBorrowActionPerformed
        int i = tbBorrow.getSelectedRow();
        if (i >= 0) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String borrow_date = sdf.format(dateChooser.getDate());
            int location = Integer.parseInt(tbBorrow.getValueAt(i, 0).toString());
            String status = statusBorrow();
            BorrowDTO br = new BorrowDTO(location, staff.getStaff_id(), reader.getReader_id(), borrow_date, status);
            int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa", "", JOptionPane.YES_NO_OPTION);
            if (a == JOptionPane.YES_OPTION) {
                int j = borrowBUS.deleteBorrow(br);
                if (j > 0) {
                    loadBorrow();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn vào table");
        }
    }//GEN-LAST:event_btnDeleteBorrowActionPerformed

    private void btnListPunishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPunishActionPerformed
        FrameTablePunish punish = new FrameTablePunish();
        punish.setVisible(true);
        punish.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnListPunishActionPerformed

    private void btnResetBorrowDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetBorrowDetailActionPerformed
        loadBorrowDetail();
    }//GEN-LAST:event_btnResetBorrowDetailActionPerformed

    private void btnEditBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBorrowActionPerformed
        int i = tbBorrow.getSelectedRow();
        if (i >= 0) {
            if (dateChooser.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Bạn chưa chọn ngày");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String borrow_date = sdf.format(dateChooser.getDate());
            int location = Integer.parseInt(tbBorrow.getValueAt(i, 0).toString());
            String status = statusBorrow();
            BorrowDTO borrow = new BorrowDTO(location, staff.getStaff_id(), reader.getReader_id(), borrow_date, status);
            int j = borrowBUS.editBorrow(borrow);
            if (j > 0) {
                loadBorrow();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn vào table");
        }
    }//GEN-LAST:event_btnEditBorrowActionPerformed

    private void btnAddBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBorrowActionPerformed
        if (dateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn ngày");
            return;
        }
        if (!rdmuon.isSelected() && !rdtra.isSelected()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn tình trạng");
            return;
        }
        // staff id
        String selectedStaffId = (String) cbStaffId.getSelectedItem();
        if (selectedStaffId.equals("0-Chọn mã nhân viên")) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn mã nhân viên", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String[] parts1 = selectedStaffId.split("-");
        int staffid = Integer.parseInt(parts1[0]);
        //reader id
        String selectedReaderId = (String) cbReaderId.getSelectedItem();
        if (selectedReaderId.equals("0-Chọn mã độc giả")) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn mã độc giả", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String[] parts2 = selectedReaderId.split("-");
        int readerId = Integer.parseInt(parts2[0]);
        String status = statusBorrow();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(dateChooser.getDate());
        BorrowDTO borrow = new BorrowDTO(0, staffid, readerId, date, status);
        int j = borrowBUS.addBorrow(borrow);
        if (j > 0) {
            loadBorrow();
        }
    }//GEN-LAST:event_btnAddBorrowActionPerformed

    public void loadStaffId() {
        cbStaffId.removeAllItems();
        ArrayList<StaffDTO> staffarr = staffBUS.getListStaff();
        cbStaffId.addItem("0-Chọn mã nhân viên");
        for (StaffDTO staff : staffarr) {
            cbStaffId.addItem((staff.getStaff_id()) + "-" + staff.getStaff_name());
        }
    }

    public void loadReaderId() {
        cbReaderId.removeAllItems();
        ArrayList<ReaderDTO> readerarr = readerBUS.getListReader();
        cbReaderId.addItem("0-Chọn mã độc giả");
        for (ReaderDTO reader : readerarr) {
            cbReaderId.addItem(reader.getReader_id() + "-" + reader.getReaderName());
        }
    }

    private void btnSearchBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBorrowActionPerformed
        if (!isNumber(txtSearchBorrow.getText())) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập vào số !");
            return;
        }
        int id = Integer.parseInt(txtSearchBorrow.getText());
        BorrowDTO borrow = borrowBUS.searchBorrow(id);
        if (borrow == null) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy thông tin !");
        } else {
            dtBorrow.setRowCount(0);
            Vector<Object> vec = new Vector<Object>();
            vec.add(borrow.getBorrow_id());
            vec.add(borrow.getStaff_id());
            vec.add(borrow.getReader_id());
            vec.add(borrow.getBorrow_date());
            vec.add(borrow.getStatus());
            dtBorrow.addRow(vec);
        }
    }//GEN-LAST:event_btnSearchBorrowActionPerformed

    private void btnPunishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPunishActionPerformed
        int selectedRow = tbBorrow.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn vào phiếu mượn");
            return;
        } else {
            id = dtBorrow.getValueAt(selectedRow, 0).toString();
            new PunishGUI().setVisible(true);
        }

    }//GEN-LAST:event_btnPunishActionPerformed
    public static ArrayList<BorrowDetailDTO> borrowdetail = new ArrayList<BorrowDetailDTO>();
    public static ArrayList<StaffDTO> liststaff = new ArrayList<StaffDTO>();
    public static ArrayList<ReaderDTO> listreader = new ArrayList<ReaderDTO>();

    // click table
    private void tbBorrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBorrowMouseClicked

        int i = tbBorrow.getSelectedRow();
        if (i >= 0) {

            txtBorrowId.setText(dtBorrow.getValueAt(i, 0).toString());
            id = (dtBorrow.getValueAt(i, 0).toString());

            String staffId = tbBorrow.getValueAt(i, 1).toString();
            String readerId = tbBorrow.getValueAt(i, 2).toString();
//            cbStaffId.setSelectedItem(staffId);
//            cbReaderId.setSelectedItem(readerId);
            try {
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) dtBorrow.getValueAt(i, 3).toString());
                dateChooser.setDate(date);
            } catch (Exception e) {
                e.printStackTrace();
            }
            String status = tbBorrow.getValueAt(i, 4).toString();

            if (status.equals("Đã mượn")) {
                rdmuon.setSelected(true);
                rdmuon.setSelected(false);
            } else if (status.equals("Đã Trả")) {
                rdtra.setSelected(false);
                rdtra.setSelected(true);
            }

            for (int j = 0; j < liststaff.size(); j++) {
                if (liststaff.get(j).getStaff_id() == Integer.parseInt(dtBorrow.getValueAt(i, 1).toString())) {
                    cbStaffId.setSelectedItem(j);
                    break;
                }
            }
            for (int j = 0; j < listreader.size(); j++) {
                if (listreader.get(j).getReader_id() == Integer.parseInt(dtBorrow.getValueAt(i, 2).toString())) {
                    cbReaderId.setSelectedItem(j);
                    break;
                }
            }

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            borrowdetail = BorrowDetailDAL.getListBorrow();
            dtBorrowDetail = (DefaultTableModel) tbBorrowDetail.getModel();
            dtBorrowDetail.setRowCount(0);
            for (int k = 0; k < borrowdetail.size(); k++) {
                if (borrowdetail.get(k).getBorrow_id() == Integer.parseInt(dtBorrow.getValueAt(i, 0).toString())) {
                    Vector<Object> vec = new Vector<Object>();
                    vec.add(borrowdetail.get(k).getBorrowDetail_id());
                    vec.add(borrowdetail.get(k).getBorrow_id());
                    vec.add(borrowdetail.get(k).getBook_id());
                    vec.add(borrowdetail.get(k).getPay_day());
                    vec.add(borrowdetail.get(k).getNote());
                    dtBorrowDetail.addRow(vec);
                }
            }

        }
    }

    private boolean isItemExists(JComboBox comboBox, String item) {
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            if (comboBox.getItemAt(i).equals(item)) {
                return true;
            }
        }
        return false;
    }//GEN-LAST:event_tbBorrowMouseClicked

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        FrameTableBook book = new FrameTableBook();
        book.setVisible(true);
        book.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnBookActionPerformed

    private void tbBorrowDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBorrowDetailMouseClicked
        int i = tbBorrowDetail.getSelectedRow();
        if (i >= 0) {
            Date date2;
            try {
                date2 = new SimpleDateFormat("yyyy-MM-dd").parse((String) dtBorrowDetail.getValueAt(i, 3).toString());
                dateChooser_pay.setDate(date2);
                txtBookIdBorrow.setText(dtBorrowDetail.getValueAt(i, 2).toString());
                txtNote.setText(dtBorrowDetail.getValueAt(i, 4).toString());
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tbBorrowDetailMouseClicked

    private void btnAddBorrowDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBorrowDetailActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String ngaymuon2;
        String ngaytra;
        try {
            String txtNoteValue  = "";
            ngaytra = sdf.format(dateChooser_pay.getDate());
            ngaymuon2 = sdf.format(dateChooser.getDate());
            if (sdf.parse(ngaymuon2).after(sdf.parse(ngaytra))) {
                txtNoteValue = "Đã hết hạn";
            } else if (sdf.parse(ngaytra).after(sdf.parse(ngaymuon2))) {
                txtNoteValue = "Chưa hết hạn";
            } else {
                txtNoteValue = "Hôm nay là hạn cuối";
            } 
            txtNote.setText(txtNoteValue);
        } catch (Exception e2) {
            JOptionPane.showMessageDialog(null, "Ngày sai");
            return;
        }
        if (!isNumber(txtBorrowId.getText())) {
            JOptionPane.showMessageDialog(null, "Mã phiếu mượn sai");
            return;
        }
        if (!isNumber(txtBorrowId.getText())) {
            JOptionPane.showMessageDialog(null, "Mã phiếu mượn sai");
            return;
        }
        if (!isNumber(txtBookIdBorrow.getText())) {
            JOptionPane.showMessageDialog(null, "Mã sách mượn sai");
            return;
        }

        BorrowDetailDTO brdt = new BorrowDetailDTO(0, Integer.parseInt(txtBorrowId.getText()),
                Integer.parseInt(txtBookIdBorrow.getText()), ngaymuon2, ngaytra, txtNote.getText());
        int j = borrowDetailBUS.addBorrowDetail(brdt);
        if (j > 0) {
            loadBorrowDetail();
        }
    }//GEN-LAST:event_btnAddBorrowDetailActionPerformed

    private void btnDeleteBorrowDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBorrowDetailActionPerformed
        int i = tbBorrowDetail.getSelectedRow();
        if (i >= 0) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String borrow_pay = sdf.format(dateChooser_pay.getDate());
            int location = Integer.parseInt(tbBorrowDetail.getValueAt(i, 0).toString());
            int borrow_id = Integer.parseInt(txtBorrowId.getText());
            int book_id = Integer.parseInt(txtBookIdBorrow.getText());
            BorrowDetailDTO brdt = new BorrowDetailDTO(location, borrow_id, book_id, borrow_pay, txtNote.getText());
            int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa", "", JOptionPane.YES_NO_OPTION);
            if (a == JOptionPane.YES_OPTION) {
                int j = borrowDetailBUS.deleteBorrowDetail(brdt);
                if (j > 0) {
                    loadBorrowDetail();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn vào table");
        }

    }//GEN-LAST:event_btnDeleteBorrowDetailActionPerformed

    private void btnEditBorrowDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBorrowDetailActionPerformed
//        int i = tbBorrowDetail.getSelectedRow();
//        if (i >= 0) {
//            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//            String ngaymuon2;
//            String ngaytra;
//            try {
//                ngaytra = sdf.format(dateChooser_pay.getDate());
//                ngaymuon2 = sdf.format(dateChooser.getDate());
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//                int mactpm = Integer.parseInt(dtBorrowDetail.getValueAt(i, 0).toString());
//                int mapm = Integer.parseInt(dtBorrowDetail.getValueAt(i, 1).toString());
//                BorrowDetailDTO ctpm = new BorrowDetailDTO(mactpm, mapm, Integer.parseInt(txtBookIdBorrow.getText()),
//                        ngaymuon2, ngaytra, txtNote.getText());
//                int j = borrowDetailBUS.editBorrowDetail(ctpm);
//                if (j > 0) {
//                    loadBorrowDetail();
//                }
//            }else {
//            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn vào table");
//        }
    }//GEN-LAST:event_btnEditBorrowDetailActionPerformed

    public static ArrayList<BorrowDTO> listborrow = new ArrayList<BorrowDTO>();

    public void loadBorrow() {
        listborrow = null;
        listborrow = BorrowDAL.getListBorrow();
        dtBorrow = (DefaultTableModel) tbBorrow.getModel();
        dtBorrow.setRowCount(0);

        for (BorrowDTO borrow : listborrow) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(borrow.getBorrow_id());
            vec.add(borrow.getStaff_id());
            vec.add(borrow.getReader_id());
            vec.add(borrow.getBorrow_date());
            vec.add(borrow.getStatus());
            dtBorrow.addRow(vec);
        }
    }
    public static ArrayList<BorrowDetailDTO> listborrowdetail = new ArrayList<BorrowDetailDTO>();

    public void loadBorrowDetail() {
        listborrowdetail = null;
        listborrowdetail = BorrowDetailDAL.getListBorrow();
        dtBorrowDetail = (DefaultTableModel) tbBorrowDetail.getModel();
        dtBorrowDetail.setRowCount(0);
        for (BorrowDetailDTO pm : listborrowdetail) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(pm.getBorrowDetail_id());
            vec.add(pm.getBorrow_id());
            vec.add(pm.getBook_id());
            vec.add(pm.getPay_day());
            vec.add(pm.getNote());
            dtBorrowDetail.addRow(vec);
        }
    }

    public String statusBorrow() {
        if (rdmuon.isSelected()) {
            return "Đang Mượn";
        }
        return "Đã Trả";
    }

    public static boolean isNumber(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (Exception e) {
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBorrow;
    private javax.swing.JButton btnAddBorrowDetail;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnDeleteBorrow;
    private javax.swing.JButton btnDeleteBorrowDetail;
    private javax.swing.JButton btnEditBorrow;
    private javax.swing.JButton btnEditBorrowDetail;
    private javax.swing.JButton btnListPunish;
    private javax.swing.JButton btnPunish;
    private javax.swing.JButton btnResetBorrow;
    private javax.swing.JButton btnResetBorrowDetail;
    private javax.swing.JButton btnSearchBorrow;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbReaderId;
    private javax.swing.JComboBox<String> cbStaffId;
    private com.toedter.calendar.JDateChooser dateChooser;
    private com.toedter.calendar.JDateChooser dateChooser_pay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JRadioButton rdmuon;
    public javax.swing.JRadioButton rdtra;
    private javax.swing.JTable tbBorrow;
    private javax.swing.JTable tbBorrowDetail;
    public static javax.swing.JTextField txtBookIdBorrow;
    private javax.swing.JTextField txtBorrowId;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtSearchBorrow;
    // End of variables declaration//GEN-END:variables
}
