/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAL.SupplierDAL;
import DTO.StaffDTO;
import DTO.SupplierDTO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hoangtuan
 */
public class FrameTableSuperlierGUI extends javax.swing.JFrame {

    DefaultTableModel dftSupplier;

    /**
     * Creates new form FrameTableSuperlierGUI
     */
    public FrameTableSuperlierGUI() {
        initComponents();
        dftSupplier = (DefaultTableModel) tbNCC.getModel();
        loadSupplier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearchNCC = new javax.swing.JTextField();
        btnSearchNCC = new javax.swing.JButton();
        btnSaveNCCId = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNCC = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tìm Kiếm");

        btnSearchNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/12_search.png"))); // NOI18N
        btnSearchNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNCCActionPerformed(evt);
            }
        });

        btnSaveNCCId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSaveNCCId.setText("Lưu");
        btnSaveNCCId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNCCIdActionPerformed(evt);
            }
        });

        tbNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã NCC", "Tên NCC"
            }
        ));
        jScrollPane1.setViewportView(tbNCC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(txtSearchNCC)
                .addGap(18, 18, 18)
                .addComponent(btnSearchNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(btnSaveNCCId, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearchNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchNCC))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSaveNCCId)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveNCCIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNCCIdActionPerformed
        int i = tbNCC.getSelectedRow();
        if (i >= 0) {
            String supplier_id = dftSupplier.getValueAt(i, 0).toString();
            CouponGUI.txtSupplierId.setText(supplier_id);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Chưa chọn vào table");
        }

    }//GEN-LAST:event_btnSaveNCCIdActionPerformed

    private void btnSearchNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNCCActionPerformed
        try {
            dftSupplier.setRowCount(0);
            if (txtSearchNCC.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập vào nội dung !");
                loadSupplier();
                return;
            }
            String s = txtSearchNCC.getText().toLowerCase();
            listsupplier = null;
            listsupplier = SupplierDAL.getListSupplier();
            dftSupplier.setRowCount(0);
            for (SupplierDTO supp : listsupplier) {
                if (supp.getSupplier_name().toLowerCase().contains(s)) {
                    // đúng điều kiện thì đẩy nó vào table
                    Vector<Object> vec = new Vector<Object>();
                    vec.add(supp.getSupplier_id());
                    vec.add(supp.getSupplier_name());
                    dftSupplier.addRow(vec);
                }
                // .DesignLai.dtm.addRow(vec);
            }
        } catch (Exception e) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_btnSearchNCCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTableSuperlierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTableSuperlierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTableSuperlierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTableSuperlierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTableSuperlierGUI().setVisible(true);
            }
        });
    }
    public static ArrayList<SupplierDTO> listsupplier = new ArrayList<SupplierDTO>();

    public void loadSupplier() {
        listsupplier = null;
        listsupplier = SupplierDAL.getListSupplier();
        dftSupplier.setRowCount(0);
        for (SupplierDTO supplier : listsupplier) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(supplier.getSupplier_id());

            vec.add(supplier.getSupplier_name());
            dftSupplier.addRow(vec);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveNCCId;
    private javax.swing.JButton btnSearchNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbNCC;
    private javax.swing.JTextField txtSearchNCC;
    // End of variables declaration//GEN-END:variables
}
