/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAL.StaffDAL;
import DTO.StaffDTO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import javax.swing.JOptionPane;

public class FrameTableStaffGUI extends javax.swing.JFrame {

    /**
     * Creates new form FrameTableStaffGUI
     */
    DefaultTableModel dftStaff;

    public FrameTableStaffGUI() {
        initComponents();
        dftStaff = (DefaultTableModel) tbStaff.getModel();
        loadStaff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSearchBook = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStaff = new javax.swing.JTable();
        btnSaveStaffId = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tìm Kiếm");

        btnSearchBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/12_search.png"))); // NOI18N
        btnSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBookActionPerformed(evt);
            }
        });

        tbStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Họ Tên", "Năm Sinh", "Giới Tính", "Địa Chỉ", "SĐT"
            }
        ));
        jScrollPane1.setViewportView(tbStaff);

        btnSaveStaffId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSaveStaffId.setText("Lưu");
        btnSaveStaffId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveStaffIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(txtSearch)
                .addGap(26, 26, 26)
                .addComponent(btnSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(btnSaveStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSearchBook)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveStaffId)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveStaffIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStaffIdActionPerformed
        int i = tbStaff.getSelectedRow();
        if (i >= 0) {
            String staff_id = dftStaff.getValueAt(i, 0).toString();
            CouponGUI.txtStaffId.setText(staff_id);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Chưa chọn vào table");
        }
    }//GEN-LAST:event_btnSaveStaffIdActionPerformed
    public static ArrayList<StaffDTO> liststaff = new ArrayList<StaffDTO>();
    private void btnSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBookActionPerformed
        try {
            dftStaff.setRowCount(0);
            ////// mỗi lần gọi lại xoá mịa cái table đi
            if (txtSearch.getText().isEmpty()) {
                // nếu txtfield rỗng thì hiển thị lại cái bảng đầy đủ
//                loadStaff(); // hàm đẩy từ csdl vào bảng //
                JOptionPane.showMessageDialog(null, "Vui lòng nhập vào nội dung !");
                loadStaff();
                return;
            }
            String s = txtSearch.getText().toLowerCase(); // chuyển chữ trong txtfield về chữ thường
            // nhờ v mà seach chữ thường chữ hoa gì cũng ra hết
            liststaff = null;
            liststaff = StaffDAL.getListStaff();
            dftStaff.setRowCount(0);
            for (StaffDTO nv : liststaff) {
                if (nv.getStaff_name().toLowerCase().contains(s)) {
                    // đúng điều kiện thì đẩy nó vào table
                    Vector<Object> vec = new Vector<Object>();
                    vec.add(nv.getStaff_id());
                    vec.add(nv.getStaff_name());
                    vec.add(nv.getBirthYear());
                    vec.add(nv.getGender());
                    vec.add(nv.getAddress());
                    vec.add(nv.getPhoneNumber());
                    dftStaff.addRow(vec);
                }
                // .DesignLai.dtm.addRow(vec);
            }
        } catch (Exception e) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_btnSearchBookActionPerformed

    public void loadStaff() {
        liststaff = null;
        liststaff = StaffDAL.getListStaff();
        dftStaff.setRowCount(0);
        for (StaffDTO nv : liststaff) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(nv.getStaff_id());
            vec.add(nv.getStaff_name());
            vec.add(nv.getBirthYear());
            vec.add(nv.getGender());
            vec.add(nv.getAddress());
            vec.add(nv.getPhoneNumber());
            dftStaff.addRow(vec);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTableStaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTableStaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTableStaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTableStaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTableStaffGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveStaffId;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbStaff;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
