/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.BorrowDetailBUS;
import BUS.CouponDetailBUS;
import DAL.CouponDetailDAL;
import DTO.CouponDetailDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hoangtuan
 */
public class StatisticalGUI extends javax.swing.JPanel {
    
    private String selectYear = "";
    public static ArrayList<CouponDetailDTO> liststcp = new ArrayList<>();
    private DefaultTableModel dftStatistical;
    private final ButtonGroup chooserGroup;
    CouponDetailBUS couponDetailBUS = new CouponDetailBUS();
    public StatisticalGUI() {
        initComponents();
        dftStatistical = (DefaultTableModel) tbStatisticalCoupon.getModel();
        loadStatisticalCoupon();
        chooserGroup = new ButtonGroup();
        chooserGroup.add(rdDay);
        chooserGroup.add(rdYear);
        addYear();
    }

    public void addYear() {
        loadYear();

        cbSelectYear.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent arg0) {
                if (cbSelectYear.getSelectedIndex() > 0) {
                    selectYear = cbSelectYear.getSelectedItem().toString();
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFreeChartResources1 = new org.jfree.chart.resources.JFreeChartResources();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStatisticalCoupon = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        rdYear = new javax.swing.JRadioButton();
        rdDay = new javax.swing.JRadioButton();
        dataChooser_start = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dataChooser_end = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuantityBook = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        cbSelectYear = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();
        btnListBorrow = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbStatisticalCoupon.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tbStatisticalCoupon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã CTPN", "Mã PN", "Mã Sách", "Giá Nhập", "Số Lượng", "Thành Tiền", "Ngày Nhập", "Tên Sách"
            }
        ));
        tbStatisticalCoupon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStatisticalCouponMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbStatisticalCoupon);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1010, 227));

        jLabel1.setText("Lọc theo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 263, -1, -1));

        rdYear.setText("Năm");
        jPanel1.add(rdYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 261, -1, -1));

        rdDay.setText("Ngày");
        jPanel1.add(rdDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));
        jPanel1.add(dataChooser_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 258, 157, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("đến ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));
        jPanel1.add(dataChooser_end, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Số lượng sách nhập :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Tổng tiền:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        txtQuantityBook.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtQuantityBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 119, -1));

        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 119, -1));

        cbSelectYear.setToolTipText("");
        cbSelectYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectYearActionPerformed(evt);
            }
        });
        jPanel1.add(cbSelectYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 258, 159, -1));

        btnFilter.setText("Lọc");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        jPanel1.add(btnFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 190, 40));

        btnListBorrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6_borrow.png"))); // NOI18N
        btnListBorrow.setText("Danh Sách Phiếu Mượn");
        btnListBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListBorrowActionPerformed(evt);
            }
        });
        jPanel1.add(btnListBorrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 240, 40));

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/13_reset.png"))); // NOI18N
        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        liststcp = null;
      
        if (!rdYear.isSelected() && !rdDay.isSelected()) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn lọc theo ngày / năm");
            return;
        }
        if (selectYear.equals("") && dataChooser_start.getDate() == null && dataChooser_end.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn năm / ngày");
            loadStatisticalCoupon();
            System.out.println("alos"); 
            return;
        }
        if (selectYear !="" && rdYear.isSelected()) {
            int nam = Integer.parseInt(selectYear);
            System.out.println("alos");
            int total = 0;
            int quantity = 0;
            liststcp = null;
            liststcp = CouponDetailBUS.gI().getStatisticalByYear(Integer.parseInt(selectYear));
            dftStatistical = (DefaultTableModel) tbStatisticalCoupon.getModel();
            dftStatistical.setRowCount(0);
            for (CouponDetailDTO pn : liststcp) {
                Vector<Object> vec = new Vector<Object>();
                vec.add(pn.getCouponDetail_id());
                vec.add(pn.getCoupon_id());
                vec.add(pn.getBook_id());
                vec.add(pn.getPrice());
                vec.add(pn.getQuantity());
                vec.add(pn.getTotal());
                vec.add(pn.getDate_add());
                vec.add(pn.getBook_name());
                quantity += pn.getQuantity();
                total += pn.getTotal();
                dftStatistical.addRow(vec);
            }
            txtTotal.setText(total + "");
            txtQuantityBook.setText(quantity + "");

        } else if (dataChooser_start.getDate() != null && dataChooser_end.getDate() != null && rdDay.isSelected()) {
            int tong2 = 0;
            int soluong3 = 0;
            selectYear = "";
            cbSelectYear.setSelectedIndex(0);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date1 = sdf.format(dataChooser_start.getDate());
            String date2 = sdf.format(dataChooser_end.getDate());
            System.out.println(date2);
            liststcp = CouponDetailBUS.gI().getStatisticalByDay(date1, date2);
            dftStatistical.setRowCount(0);

            for (CouponDetailDTO pn : liststcp) {

                Vector<Object> vec = new Vector<Object>();
                vec.add(pn.getCouponDetail_id());
                vec.add(pn.getCoupon_id());
                vec.add(pn.getBook_id());
                vec.add(pn.getPrice());
                vec.add(pn.getQuantity());
                vec.add(pn.getTotal());
                vec.add(pn.getDate_add());
                vec.add(pn.getBook_name());
                dftStatistical.addRow(vec);
                soluong3 += pn.getQuantity();
                tong2 += pn.getTotal();
                // dtmctpm.addRow(vec);
            }
            txtTotal.setText(tong2 + "");
            txtQuantityBook.setText(soluong3 + "");

        }
        
    }//GEN-LAST:event_btnFilterActionPerformed
    public void loadYear() {
        cbSelectYear.addItem("");
        int year = Calendar.getInstance().get(Calendar.YEAR);
        for (int i = year; i > year - 4; i--) {
            cbSelectYear.addItem(i + "");
        }
    }
    private void cbSelectYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectYearActionPerformed
//        if (cbSelectYear.getSelectedIndex() > 0) {
//            se = cbSelectYear.getSelectedItem().toString();
//        }
    }//GEN-LAST:event_cbSelectYearActionPerformed

    private void btnListBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListBorrowActionPerformed
        digstatisborrowGUI borrow = new digstatisborrowGUI();
        borrow.setVisible(true);
        borrow.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnListBorrowActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        loadStatisticalCoupon();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tbStatisticalCouponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStatisticalCouponMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbStatisticalCouponMouseClicked

    public void loadStatisticalCoupon() {
        liststcp = null;
//        liststcp = CouponDetailBUS.gI().getStatisticalCoupon();
        liststcp = CouponDetailDAL.getStatisticalCoupon();
        dftStatistical.setRowCount(0);
        for (CouponDetailDTO cp : liststcp) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(cp.getCouponDetail_id());
            vec.add(cp.getCoupon_id());
            vec.add(cp.getBook_id());
            vec.add(cp.getPrice());
            vec.add(cp.getQuantity());
            vec.add(cp.getTotal());
            vec.add(cp.getDate_add());
            vec.add(cp.getBook_name());
            dftStatistical.addRow(vec);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnListBorrow;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbSelectYear;
    private com.toedter.calendar.JDateChooser dataChooser_end;
    private com.toedter.calendar.JDateChooser dataChooser_start;
    private org.jfree.chart.resources.JFreeChartResources jFreeChartResources1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdDay;
    private javax.swing.JRadioButton rdYear;
    private javax.swing.JTable tbStatisticalCoupon;
    private javax.swing.JTextField txtQuantityBook;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
